name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: gradle

      - name: Force Fix Project
        run: |
          # 1. Исправляем TensorFlow во всех build.gradle
          find . -name "build.gradle" -exec sed -i 's/0.0.0-nightly/2.5.0/g' {} +
          
          # 2. Добавляем архивный репозиторий jcenter и mavenCentral, так как старые библиотеки могут быть там
          find . -name "build.gradle" -exec sed -i "s/google()/google()\n        mavenCentral()\n        jcenter()/g" {} +

      - name: Grant execute permission for gradlew
        run: find . -name "gradlew" -exec chmod +x {} +

      - name: Build APK
        run: |
          GRADLE_PATH=$(find . -name "gradlew" -printf '%h\n' | head -n 1)
          cd $GRADLE_PATH
          # Запускаем сборку с игнорированием некоторых ошибок проверки
          ./gradlew assembleDebug --stacktrace -Pandroid.useAndroidX=true -Pandroid.enableJetifier=true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: esp32-cam-ai-debug
          path: "**/*.apk"
